PUT /_scripts/audit HTTP/1.1
Host: 192.168.1.26:9200
Content-Type: application/json
Content-Length: 674

{
    "script": {
        "lang": "mustache",
        "source": {
            "query": {
                "bool": {
                    "must": {
                        "match": {
                            "project": "{{id}}"
                        }
                    },
                    "filter": {
                        "range": {
                            "timestamp": {
                                "gte": "{{floor}}",
                                "lt": "{{ceiling}}",
                                "format": "{{format}}"
                            }
                        }
                    }
                }
            }
        }
    }
}